config/routes.rb
Rails.application.routes.draw do
	root 'students#index'


	get '/new' => 'students#new'
	post '/new' => 'students#index'	
	get '/index/login' => 'sessions#login'
	post 'login' => 'sessions#create'
	get '/user_home' => 'students#user_home'
	post 'logout' => 'sessions#destroy'
	post 'fill_choices' => 'students#fill_choices'
	get '/fill_choices/view_choices' => 'students#view_choices'
	get '/fill_choices/add_choices' => 'students#add_choices'
	get '/fill_choices/edit_choices' => 'students#edit_choices'
	get '/fill_choices/add_choices/show' => 'students#show'
	get 'getdata' => 'students#getdata'
	resources :students;
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allotment.rb
class Allotment < ApplicationRecord
end

app/models/allotseat.rb
class Allotseat < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/models/college.rb
class College < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def login
	end
	def create
		@student=Student.find_by_regno(params[:session][:regno])
		if @student && @student.find_by_password_digest(params[:session][:password_digest])
			session[:student_id]=@student.id
			redirect_to '/user_home'
		else
			redirect_to '/login'
		end
	end
	
	def destroy
		session[:student_id]=nil
		redirect_to '/'
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
	end
	def home
	end
	def fill_choices
	end
	def view_choices
		@college=College.all
	end
	def add_choices
		@college=College.all
	end
	def edit_choices
	end
	def show
	end
	def new
		@student=Student.new
	end
	
	def create
		@student=Student.new(student_params)
		if @student.save
			session[:student_id]=@student.id
			redirect_to '/'
		else
			redirect_to '/new'
		end
	end
	private
		def student_params
			params.require(:student).permit(:name, :dob, :gender, :phone, :rank, :email, :regno, :password_digest)
		end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/add_choices.html.erb
<form>
  <select name="dep">
    <option>select</option>
  <%= @college.each do |f| %>
    <option><%= f.college_code %></option>
  <% end %>
  </select>
 <%= $department %>
  <select name="cname">
    <option>branch name</option>
  </select>

</form>

app/views/students/edit_choices.html.erb
<h1>EDIT CHOICES</h1>

app/views/students/fill_choices.html.erb
<h1>List of available choices</h1>
<%= link_to "view choices", controller: "students", action: "view_choices" %><br>
<%= link_to "add choices", controller: "students", action: "add_choices" %><br>
<%= link_to "edit choices", controller: "students", action: "edit_choices" %><br>

app/views/students/index.html.erb
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Seat Allotment</h1>
                      
                             <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Seat Allotment</h2>
                <p>Seat is seat allotment made by us thats it <a href="http://ccmt.nic.in/webinfo/Public/Home.aspx/">EXAM 2017</a>. The theme is to reduce money and power.</p>
                
            </div>
        </div>
    </section>
                        
                    </div>
                </div>
            </div>
        </div>
    </header>D

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
       
<h1> Seat Allotment 2017</h1><br>


<%= link_to "new registration", controller: "students", action: "new" %><br>
<%= link_to "student login", controller: "sessions" , action: "login" %>

app/views/students/new.html.erb
 <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <h1 class="brand-heading">fill your details</h1>
                    <h2>About Seat Allotment</h2>
                    <%= form_for @student do |f| %>
  <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
 
    <p>
      <%= f.label :date_of_birth %><br>
      <%= f.text_field :dob %>
    </p>
  <p>
      <%= f.label :gender %><br>
      <%= f.text_field :gender %>
    </p>
    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>
    <p>
      <%= f.label :rank %><br>
      <%= f.text_field :score %>
    </p> 
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :regno %><br>
      <%= f.text_field :regno %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password_digest %>
    </p>
    <p>
      <%= f.submit %>
    </p><br>
    <%= link_to "Back", :back %>
<% end %>
                   
                
                </div>
            </div>
    </section>

app/views/students/show.html.erb
<h1>hello</h1>

app/views/students/user_home.html.erb
<h1>user home page</h1>
<%= link_to "log out", logout_path, method:"destroy" %><br>
<%= link_to "fill_choices", fill_choices_path, method:"fill_choices" %><br>
<%= link_to "Back", :back %>

app/views/students/view_choices.html.erb
<h1>Available choices</h1>

<table>
		<tr>
			<th>code</th>
			<th>name</th>
			<th> <colspan="3"></th>
		</tr>
		
		 <% @college.each do |article| %>
			<tr>
				<td><%= article.college_code %></td>
				<td><%= article.college_name %></td>
			</tr>
		 <% end %>
	</table>